platform :ios, '9.0'
use_frameworks!

target 'PrivacyKit_Example' do
  pod 'PrivacyKit', :path => '../'

  pod 'SwiftLint'

  target 'PrivacyKit_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
